version: '3'

networks:
  testing_net:
    driver: bridge

services:
  main-server:
    build:
      context: ./
    volumes:
      - ./apache:/usr/local/apache2/conf
    networks: 
      - testing_net
    ports:
      - 8010:80

  main-server2:
    build:
      context: ./caddy
    volumes:
      - ./caddy/caddy:/etc/caddy
    networks: 
      - testing_net
    ports:
      - 8015:80

  server1:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs
    networks: 
      - testing_net

  server2:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs
    networks: 
      - testing_net

  server3:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs
    networks: 
      - testing_net

  server4:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs
    networks: 
      - testing_net

  server5:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs
    networks: 
      - testing_net

  server6:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs
    networks: 
      - testing_net
